#!/bin/sh

readonly TARGET_DIR=$PWD/../linc-gh-pages

rm -rf $TARGET_DIR/*

(
  wasm-pack build --release --out-dir=$TARGET_DIR
)
(
  cd $TARGET_DIR
  git commit --all --message=deploy-$(date --iso-8601=seconds)
  git push
)
