#!/bin/sh

readonly TARGET_DIR=$PWD/../linc-gh-pages

rm -rf $TARGET_DIR/*

./build
cp -r ./static/{snippets,index.html,icons.css,style.css,tailwind.css,wasm.js,wasm_bg.wasm} $TARGET_DIR
(
  cd $TARGET_DIR
  git add .
  git commit --all --message=deploy-$(date --iso-8601=seconds)
  git push
)
