#!/bin/sh

readonly TARGET_DIR=$PWD/../linc-gh-pages

rm -rf $TARGET_DIR/*

./build
cp --recursive ./dist/* $TARGET_DIR
(
  cd $TARGET_DIR
  git add .
  git commit --all --message=deploy-$(date --iso-8601=seconds)
  git push
)
