// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ast.proto

package ast

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type_PrimitiveType int32

const (
	Type_PRIMITIVE_TYPE_UNSPECIFIED Type_PrimitiveType = 0
	Type_INT                        Type_PrimitiveType = 1
	Type_FLOAT                      Type_PrimitiveType = 2
)

var Type_PrimitiveType_name = map[int32]string{
	0: "PRIMITIVE_TYPE_UNSPECIFIED",
	1: "INT",
	2: "FLOAT",
}

var Type_PrimitiveType_value = map[string]int32{
	"PRIMITIVE_TYPE_UNSPECIFIED": 0,
	"INT":                        1,
	"FLOAT":                      2,
}

func (x Type_PrimitiveType) String() string {
	return proto.EnumName(Type_PrimitiveType_name, int32(x))
}

func (Type_PrimitiveType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{4, 0}
}

type File struct {
	NextRef              int64                 `protobuf:"varint,1,opt,name=next_ref,json=nextRef,proto3" json:"next_ref,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FunctionDefinitions  []*FunctionDefinition `protobuf:"bytes,5,rep,name=function_definitions,json=functionDefinitions,proto3" json:"function_definitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetNextRef() int64 {
	if m != nil {
		return m.NextRef
	}
	return 0
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetFunctionDefinitions() []*FunctionDefinition {
	if m != nil {
		return m.FunctionDefinitions
	}
	return nil
}

type Expression struct {
	Ref int64 `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Expression_EmptyValue
	//	*Expression_BoolValue
	//	*Expression_IntValue
	//	*Expression_FloatValue
	//	*Expression_StringValue
	//	*Expression_ListValue
	//	*Expression_IfValue
	//	*Expression_FunctionApplicationValue
	//	*Expression_RefValue
	//	*Expression_ExternalRefValue
	Value                isExpression_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Expression) Reset()         { *m = Expression{} }
func (m *Expression) String() string { return proto.CompactTextString(m) }
func (*Expression) ProtoMessage()    {}
func (*Expression) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{1}
}

func (m *Expression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression.Unmarshal(m, b)
}
func (m *Expression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression.Marshal(b, m, deterministic)
}
func (m *Expression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression.Merge(m, src)
}
func (m *Expression) XXX_Size() int {
	return xxx_messageInfo_Expression.Size(m)
}
func (m *Expression) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression.DiscardUnknown(m)
}

var xxx_messageInfo_Expression proto.InternalMessageInfo

func (m *Expression) GetRef() int64 {
	if m != nil {
		return m.Ref
	}
	return 0
}

type isExpression_Value interface {
	isExpression_Value()
}

type Expression_EmptyValue struct {
	EmptyValue int32 `protobuf:"varint,9,opt,name=empty_value,json=emptyValue,proto3,oneof"`
}

type Expression_BoolValue struct {
	BoolValue *Expression_Bool `protobuf:"bytes,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Expression_IntValue struct {
	IntValue *Expression_Int `protobuf:"bytes,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Expression_FloatValue struct {
	FloatValue *Expression_Float `protobuf:"bytes,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Expression_StringValue struct {
	StringValue *Expression_String `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Expression_ListValue struct {
	ListValue *Expression_List `protobuf:"bytes,6,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Expression_IfValue struct {
	IfValue *Expression_If `protobuf:"bytes,7,opt,name=if_value,json=ifValue,proto3,oneof"`
}

type Expression_FunctionApplicationValue struct {
	FunctionApplicationValue *Expression_FunctionApplication `protobuf:"bytes,8,opt,name=function_application_value,json=functionApplicationValue,proto3,oneof"`
}

type Expression_RefValue struct {
	RefValue *Expression_Ref `protobuf:"bytes,12,opt,name=ref_value,json=refValue,proto3,oneof"`
}

type Expression_ExternalRefValue struct {
	ExternalRefValue *Expression_ExternalRef `protobuf:"bytes,13,opt,name=external_ref_value,json=externalRefValue,proto3,oneof"`
}

func (*Expression_EmptyValue) isExpression_Value() {}

func (*Expression_BoolValue) isExpression_Value() {}

func (*Expression_IntValue) isExpression_Value() {}

func (*Expression_FloatValue) isExpression_Value() {}

func (*Expression_StringValue) isExpression_Value() {}

func (*Expression_ListValue) isExpression_Value() {}

func (*Expression_IfValue) isExpression_Value() {}

func (*Expression_FunctionApplicationValue) isExpression_Value() {}

func (*Expression_RefValue) isExpression_Value() {}

func (*Expression_ExternalRefValue) isExpression_Value() {}

func (m *Expression) GetValue() isExpression_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Expression) GetEmptyValue() int32 {
	if x, ok := m.GetValue().(*Expression_EmptyValue); ok {
		return x.EmptyValue
	}
	return 0
}

func (m *Expression) GetBoolValue() *Expression_Bool {
	if x, ok := m.GetValue().(*Expression_BoolValue); ok {
		return x.BoolValue
	}
	return nil
}

func (m *Expression) GetIntValue() *Expression_Int {
	if x, ok := m.GetValue().(*Expression_IntValue); ok {
		return x.IntValue
	}
	return nil
}

func (m *Expression) GetFloatValue() *Expression_Float {
	if x, ok := m.GetValue().(*Expression_FloatValue); ok {
		return x.FloatValue
	}
	return nil
}

func (m *Expression) GetStringValue() *Expression_String {
	if x, ok := m.GetValue().(*Expression_StringValue); ok {
		return x.StringValue
	}
	return nil
}

func (m *Expression) GetListValue() *Expression_List {
	if x, ok := m.GetValue().(*Expression_ListValue); ok {
		return x.ListValue
	}
	return nil
}

func (m *Expression) GetIfValue() *Expression_If {
	if x, ok := m.GetValue().(*Expression_IfValue); ok {
		return x.IfValue
	}
	return nil
}

func (m *Expression) GetFunctionApplicationValue() *Expression_FunctionApplication {
	if x, ok := m.GetValue().(*Expression_FunctionApplicationValue); ok {
		return x.FunctionApplicationValue
	}
	return nil
}

func (m *Expression) GetRefValue() *Expression_Ref {
	if x, ok := m.GetValue().(*Expression_RefValue); ok {
		return x.RefValue
	}
	return nil
}

func (m *Expression) GetExternalRefValue() *Expression_ExternalRef {
	if x, ok := m.GetValue().(*Expression_ExternalRefValue); ok {
		return x.ExternalRefValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Expression) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Expression_EmptyValue)(nil),
		(*Expression_BoolValue)(nil),
		(*Expression_IntValue)(nil),
		(*Expression_FloatValue)(nil),
		(*Expression_StringValue)(nil),
		(*Expression_ListValue)(nil),
		(*Expression_IfValue)(nil),
		(*Expression_FunctionApplicationValue)(nil),
		(*Expression_RefValue)(nil),
		(*Expression_ExternalRefValue)(nil),
	}
}

type Expression_Hole struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Expression_Hole) Reset()         { *m = Expression_Hole{} }
func (m *Expression_Hole) String() string { return proto.CompactTextString(m) }
func (*Expression_Hole) ProtoMessage()    {}
func (*Expression_Hole) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{1, 0}
}

func (m *Expression_Hole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression_Hole.Unmarshal(m, b)
}
func (m *Expression_Hole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression_Hole.Marshal(b, m, deterministic)
}
func (m *Expression_Hole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression_Hole.Merge(m, src)
}
func (m *Expression_Hole) XXX_Size() int {
	return xxx_messageInfo_Expression_Hole.Size(m)
}
func (m *Expression_Hole) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression_Hole.DiscardUnknown(m)
}

var xxx_messageInfo_Expression_Hole proto.InternalMessageInfo

type Expression_Bool struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Expression_Bool) Reset()         { *m = Expression_Bool{} }
func (m *Expression_Bool) String() string { return proto.CompactTextString(m) }
func (*Expression_Bool) ProtoMessage()    {}
func (*Expression_Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{1, 1}
}

func (m *Expression_Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression_Bool.Unmarshal(m, b)
}
func (m *Expression_Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression_Bool.Marshal(b, m, deterministic)
}
func (m *Expression_Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression_Bool.Merge(m, src)
}
func (m *Expression_Bool) XXX_Size() int {
	return xxx_messageInfo_Expression_Bool.Size(m)
}
func (m *Expression_Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Expression_Bool proto.InternalMessageInfo

func (m *Expression_Bool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type Expression_Int struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Expression_Int) Reset()         { *m = Expression_Int{} }
func (m *Expression_Int) String() string { return proto.CompactTextString(m) }
func (*Expression_Int) ProtoMessage()    {}
func (*Expression_Int) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{1, 2}
}

func (m *Expression_Int) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression_Int.Unmarshal(m, b)
}
func (m *Expression_Int) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression_Int.Marshal(b, m, deterministic)
}
func (m *Expression_Int) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression_Int.Merge(m, src)
}
func (m *Expression_Int) XXX_Size() int {
	return xxx_messageInfo_Expression_Int.Size(m)
}
func (m *Expression_Int) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression_Int.DiscardUnknown(m)
}

var xxx_messageInfo_Expression_Int proto.InternalMessageInfo

func (m *Expression_Int) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Expression_Float struct {
	Value                float32  `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Expression_Float) Reset()         { *m = Expression_Float{} }
func (m *Expression_Float) String() string { return proto.CompactTextString(m) }
func (*Expression_Float) ProtoMessage()    {}
func (*Expression_Float) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{1, 3}
}

func (m *Expression_Float) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression_Float.Unmarshal(m, b)
}
func (m *Expression_Float) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression_Float.Marshal(b, m, deterministic)
}
func (m *Expression_Float) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression_Float.Merge(m, src)
}
func (m *Expression_Float) XXX_Size() int {
	return xxx_messageInfo_Expression_Float.Size(m)
}
func (m *Expression_Float) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression_Float.DiscardUnknown(m)
}

var xxx_messageInfo_Expression_Float proto.InternalMessageInfo

func (m *Expression_Float) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Expression_String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Expression_String) Reset()         { *m = Expression_String{} }
func (m *Expression_String) String() string { return proto.CompactTextString(m) }
func (*Expression_String) ProtoMessage()    {}
func (*Expression_String) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{1, 4}
}

func (m *Expression_String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression_String.Unmarshal(m, b)
}
func (m *Expression_String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression_String.Marshal(b, m, deterministic)
}
func (m *Expression_String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression_String.Merge(m, src)
}
func (m *Expression_String) XXX_Size() int {
	return xxx_messageInfo_Expression_String.Size(m)
}
func (m *Expression_String) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression_String.DiscardUnknown(m)
}

var xxx_messageInfo_Expression_String proto.InternalMessageInfo

func (m *Expression_String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Expression_List struct {
	Values               []*Expression `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Expression_List) Reset()         { *m = Expression_List{} }
func (m *Expression_List) String() string { return proto.CompactTextString(m) }
func (*Expression_List) ProtoMessage()    {}
func (*Expression_List) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{1, 5}
}

func (m *Expression_List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression_List.Unmarshal(m, b)
}
func (m *Expression_List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression_List.Marshal(b, m, deterministic)
}
func (m *Expression_List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression_List.Merge(m, src)
}
func (m *Expression_List) XXX_Size() int {
	return xxx_messageInfo_Expression_List.Size(m)
}
func (m *Expression_List) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression_List.DiscardUnknown(m)
}

var xxx_messageInfo_Expression_List proto.InternalMessageInfo

func (m *Expression_List) GetValues() []*Expression {
	if m != nil {
		return m.Values
	}
	return nil
}

type Expression_If struct {
	Cond                 *Expression `protobuf:"bytes,1,opt,name=cond,proto3" json:"cond,omitempty"`
	True                 *Expression `protobuf:"bytes,2,opt,name=true,proto3" json:"true,omitempty"`
	False                *Expression `protobuf:"bytes,3,opt,name=false,proto3" json:"false,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Expression_If) Reset()         { *m = Expression_If{} }
func (m *Expression_If) String() string { return proto.CompactTextString(m) }
func (*Expression_If) ProtoMessage()    {}
func (*Expression_If) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{1, 6}
}

func (m *Expression_If) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression_If.Unmarshal(m, b)
}
func (m *Expression_If) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression_If.Marshal(b, m, deterministic)
}
func (m *Expression_If) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression_If.Merge(m, src)
}
func (m *Expression_If) XXX_Size() int {
	return xxx_messageInfo_Expression_If.Size(m)
}
func (m *Expression_If) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression_If.DiscardUnknown(m)
}

var xxx_messageInfo_Expression_If proto.InternalMessageInfo

func (m *Expression_If) GetCond() *Expression {
	if m != nil {
		return m.Cond
	}
	return nil
}

func (m *Expression_If) GetTrue() *Expression {
	if m != nil {
		return m.True
	}
	return nil
}

func (m *Expression_If) GetFalse() *Expression {
	if m != nil {
		return m.False
	}
	return nil
}

type Expression_FunctionApplication struct {
	Function             int64         `protobuf:"varint,1,opt,name=function,proto3" json:"function,omitempty"`
	Arguments            []*Expression `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Expression_FunctionApplication) Reset()         { *m = Expression_FunctionApplication{} }
func (m *Expression_FunctionApplication) String() string { return proto.CompactTextString(m) }
func (*Expression_FunctionApplication) ProtoMessage()    {}
func (*Expression_FunctionApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{1, 7}
}

func (m *Expression_FunctionApplication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression_FunctionApplication.Unmarshal(m, b)
}
func (m *Expression_FunctionApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression_FunctionApplication.Marshal(b, m, deterministic)
}
func (m *Expression_FunctionApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression_FunctionApplication.Merge(m, src)
}
func (m *Expression_FunctionApplication) XXX_Size() int {
	return xxx_messageInfo_Expression_FunctionApplication.Size(m)
}
func (m *Expression_FunctionApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression_FunctionApplication.DiscardUnknown(m)
}

var xxx_messageInfo_Expression_FunctionApplication proto.InternalMessageInfo

func (m *Expression_FunctionApplication) GetFunction() int64 {
	if m != nil {
		return m.Function
	}
	return 0
}

func (m *Expression_FunctionApplication) GetArguments() []*Expression {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type Expression_Ref struct {
	Ref                  int64    `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Expression_Ref) Reset()         { *m = Expression_Ref{} }
func (m *Expression_Ref) String() string { return proto.CompactTextString(m) }
func (*Expression_Ref) ProtoMessage()    {}
func (*Expression_Ref) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{1, 8}
}

func (m *Expression_Ref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression_Ref.Unmarshal(m, b)
}
func (m *Expression_Ref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression_Ref.Marshal(b, m, deterministic)
}
func (m *Expression_Ref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression_Ref.Merge(m, src)
}
func (m *Expression_Ref) XXX_Size() int {
	return xxx_messageInfo_Expression_Ref.Size(m)
}
func (m *Expression_Ref) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression_Ref.DiscardUnknown(m)
}

var xxx_messageInfo_Expression_Ref proto.InternalMessageInfo

func (m *Expression_Ref) GetRef() int64 {
	if m != nil {
		return m.Ref
	}
	return 0
}

type Expression_ExternalRef struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Expression_ExternalRef) Reset()         { *m = Expression_ExternalRef{} }
func (m *Expression_ExternalRef) String() string { return proto.CompactTextString(m) }
func (*Expression_ExternalRef) ProtoMessage()    {}
func (*Expression_ExternalRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{1, 9}
}

func (m *Expression_ExternalRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression_ExternalRef.Unmarshal(m, b)
}
func (m *Expression_ExternalRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression_ExternalRef.Marshal(b, m, deterministic)
}
func (m *Expression_ExternalRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression_ExternalRef.Merge(m, src)
}
func (m *Expression_ExternalRef) XXX_Size() int {
	return xxx_messageInfo_Expression_ExternalRef.Size(m)
}
func (m *Expression_ExternalRef) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression_ExternalRef.DiscardUnknown(m)
}

var xxx_messageInfo_Expression_ExternalRef proto.InternalMessageInfo

func (m *Expression_ExternalRef) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Expression_ExternalRef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FunctionDefinition struct {
	Ref                  int64       `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Label                *Label      `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Arguments            []*Argument `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	ReturnType           *Type       `protobuf:"bytes,4,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	Body                 *Expression `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FunctionDefinition) Reset()         { *m = FunctionDefinition{} }
func (m *FunctionDefinition) String() string { return proto.CompactTextString(m) }
func (*FunctionDefinition) ProtoMessage()    {}
func (*FunctionDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{2}
}

func (m *FunctionDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionDefinition.Unmarshal(m, b)
}
func (m *FunctionDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionDefinition.Marshal(b, m, deterministic)
}
func (m *FunctionDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionDefinition.Merge(m, src)
}
func (m *FunctionDefinition) XXX_Size() int {
	return xxx_messageInfo_FunctionDefinition.Size(m)
}
func (m *FunctionDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionDefinition proto.InternalMessageInfo

func (m *FunctionDefinition) GetRef() int64 {
	if m != nil {
		return m.Ref
	}
	return 0
}

func (m *FunctionDefinition) GetLabel() *Label {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *FunctionDefinition) GetArguments() []*Argument {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *FunctionDefinition) GetReturnType() *Type {
	if m != nil {
		return m.ReturnType
	}
	return nil
}

func (m *FunctionDefinition) GetBody() *Expression {
	if m != nil {
		return m.Body
	}
	return nil
}

type TypeAlias struct {
	Ref                  int64    `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Label                *Label   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type1                *Type    `protobuf:"bytes,20,opt,name=type1,proto3" json:"type1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeAlias) Reset()         { *m = TypeAlias{} }
func (m *TypeAlias) String() string { return proto.CompactTextString(m) }
func (*TypeAlias) ProtoMessage()    {}
func (*TypeAlias) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{3}
}

func (m *TypeAlias) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeAlias.Unmarshal(m, b)
}
func (m *TypeAlias) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeAlias.Marshal(b, m, deterministic)
}
func (m *TypeAlias) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeAlias.Merge(m, src)
}
func (m *TypeAlias) XXX_Size() int {
	return xxx_messageInfo_TypeAlias.Size(m)
}
func (m *TypeAlias) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeAlias.DiscardUnknown(m)
}

var xxx_messageInfo_TypeAlias proto.InternalMessageInfo

func (m *TypeAlias) GetRef() int64 {
	if m != nil {
		return m.Ref
	}
	return 0
}

func (m *TypeAlias) GetLabel() *Label {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *TypeAlias) GetType1() *Type {
	if m != nil {
		return m.Type1
	}
	return nil
}

type Type struct {
	Ref int64 `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Types that are valid to be assigned to Tvalue:
	//	*Type_Primitive
	//	*Type_Compound
	//	*Type_RefType_
	Tvalue               isType_Tvalue `protobuf_oneof:"tvalue"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}
func (*Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{4}
}

func (m *Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type.Unmarshal(m, b)
}
func (m *Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type.Marshal(b, m, deterministic)
}
func (m *Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type.Merge(m, src)
}
func (m *Type) XXX_Size() int {
	return xxx_messageInfo_Type.Size(m)
}
func (m *Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Type proto.InternalMessageInfo

func (m *Type) GetRef() int64 {
	if m != nil {
		return m.Ref
	}
	return 0
}

type isType_Tvalue interface {
	isType_Tvalue()
}

type Type_Primitive struct {
	Primitive Type_PrimitiveType `protobuf:"varint,10,opt,name=primitive,proto3,enum=Type_PrimitiveType,oneof"`
}

type Type_Compound struct {
	Compound *Type_CompoundType `protobuf:"bytes,11,opt,name=compound,proto3,oneof"`
}

type Type_RefType_ struct {
	RefType *Type_RefType `protobuf:"bytes,12,opt,name=ref_type,json=refType,proto3,oneof"`
}

func (*Type_Primitive) isType_Tvalue() {}

func (*Type_Compound) isType_Tvalue() {}

func (*Type_RefType_) isType_Tvalue() {}

func (m *Type) GetTvalue() isType_Tvalue {
	if m != nil {
		return m.Tvalue
	}
	return nil
}

func (m *Type) GetPrimitive() Type_PrimitiveType {
	if x, ok := m.GetTvalue().(*Type_Primitive); ok {
		return x.Primitive
	}
	return Type_PRIMITIVE_TYPE_UNSPECIFIED
}

func (m *Type) GetCompound() *Type_CompoundType {
	if x, ok := m.GetTvalue().(*Type_Compound); ok {
		return x.Compound
	}
	return nil
}

func (m *Type) GetRefType() *Type_RefType {
	if x, ok := m.GetTvalue().(*Type_RefType_); ok {
		return x.RefType
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Type) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Type_Primitive)(nil),
		(*Type_Compound)(nil),
		(*Type_RefType_)(nil),
	}
}

type Type_RefType struct {
	Ref                  int64    `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type_RefType) Reset()         { *m = Type_RefType{} }
func (m *Type_RefType) String() string { return proto.CompactTextString(m) }
func (*Type_RefType) ProtoMessage()    {}
func (*Type_RefType) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{4, 0}
}

func (m *Type_RefType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type_RefType.Unmarshal(m, b)
}
func (m *Type_RefType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type_RefType.Marshal(b, m, deterministic)
}
func (m *Type_RefType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type_RefType.Merge(m, src)
}
func (m *Type_RefType) XXX_Size() int {
	return xxx_messageInfo_Type_RefType.Size(m)
}
func (m *Type_RefType) XXX_DiscardUnknown() {
	xxx_messageInfo_Type_RefType.DiscardUnknown(m)
}

var xxx_messageInfo_Type_RefType proto.InternalMessageInfo

func (m *Type_RefType) GetRef() int64 {
	if m != nil {
		return m.Ref
	}
	return 0
}

type Type_OpaqueType struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type_OpaqueType) Reset()         { *m = Type_OpaqueType{} }
func (m *Type_OpaqueType) String() string { return proto.CompactTextString(m) }
func (*Type_OpaqueType) ProtoMessage()    {}
func (*Type_OpaqueType) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{4, 1}
}

func (m *Type_OpaqueType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type_OpaqueType.Unmarshal(m, b)
}
func (m *Type_OpaqueType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type_OpaqueType.Marshal(b, m, deterministic)
}
func (m *Type_OpaqueType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type_OpaqueType.Merge(m, src)
}
func (m *Type_OpaqueType) XXX_Size() int {
	return xxx_messageInfo_Type_OpaqueType.Size(m)
}
func (m *Type_OpaqueType) XXX_DiscardUnknown() {
	xxx_messageInfo_Type_OpaqueType.DiscardUnknown(m)
}

var xxx_messageInfo_Type_OpaqueType proto.InternalMessageInfo

func (m *Type_OpaqueType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Type_CompoundType struct {
	X                    *Type    `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    *Type    `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type_CompoundType) Reset()         { *m = Type_CompoundType{} }
func (m *Type_CompoundType) String() string { return proto.CompactTextString(m) }
func (*Type_CompoundType) ProtoMessage()    {}
func (*Type_CompoundType) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{4, 2}
}

func (m *Type_CompoundType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type_CompoundType.Unmarshal(m, b)
}
func (m *Type_CompoundType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type_CompoundType.Marshal(b, m, deterministic)
}
func (m *Type_CompoundType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type_CompoundType.Merge(m, src)
}
func (m *Type_CompoundType) XXX_Size() int {
	return xxx_messageInfo_Type_CompoundType.Size(m)
}
func (m *Type_CompoundType) XXX_DiscardUnknown() {
	xxx_messageInfo_Type_CompoundType.DiscardUnknown(m)
}

var xxx_messageInfo_Type_CompoundType proto.InternalMessageInfo

func (m *Type_CompoundType) GetX() *Type {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *Type_CompoundType) GetY() *Type {
	if m != nil {
		return m.Y
	}
	return nil
}

type TypeConstructor struct {
	Ref                  int64    `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Label                *Label   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeConstructor) Reset()         { *m = TypeConstructor{} }
func (m *TypeConstructor) String() string { return proto.CompactTextString(m) }
func (*TypeConstructor) ProtoMessage()    {}
func (*TypeConstructor) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{5}
}

func (m *TypeConstructor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeConstructor.Unmarshal(m, b)
}
func (m *TypeConstructor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeConstructor.Marshal(b, m, deterministic)
}
func (m *TypeConstructor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeConstructor.Merge(m, src)
}
func (m *TypeConstructor) XXX_Size() int {
	return xxx_messageInfo_TypeConstructor.Size(m)
}
func (m *TypeConstructor) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeConstructor.DiscardUnknown(m)
}

var xxx_messageInfo_TypeConstructor proto.InternalMessageInfo

func (m *TypeConstructor) GetRef() int64 {
	if m != nil {
		return m.Ref
	}
	return 0
}

func (m *TypeConstructor) GetLabel() *Label {
	if m != nil {
		return m.Label
	}
	return nil
}

type Pattern struct {
	Ref int64 `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Types that are valid to be assigned to Pvalue:
	//	*Pattern_TypeConstructorValue
	//	*Pattern_LabelValue
	//	*Pattern_PatternValue
	Pvalue               isPattern_Pvalue `protobuf_oneof:"pvalue"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Pattern) Reset()         { *m = Pattern{} }
func (m *Pattern) String() string { return proto.CompactTextString(m) }
func (*Pattern) ProtoMessage()    {}
func (*Pattern) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{6}
}

func (m *Pattern) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pattern.Unmarshal(m, b)
}
func (m *Pattern) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pattern.Marshal(b, m, deterministic)
}
func (m *Pattern) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pattern.Merge(m, src)
}
func (m *Pattern) XXX_Size() int {
	return xxx_messageInfo_Pattern.Size(m)
}
func (m *Pattern) XXX_DiscardUnknown() {
	xxx_messageInfo_Pattern.DiscardUnknown(m)
}

var xxx_messageInfo_Pattern proto.InternalMessageInfo

func (m *Pattern) GetRef() int64 {
	if m != nil {
		return m.Ref
	}
	return 0
}

type isPattern_Pvalue interface {
	isPattern_Pvalue()
}

type Pattern_TypeConstructorValue struct {
	TypeConstructorValue *TypeConstructor `protobuf:"bytes,2,opt,name=type_constructor_value,json=typeConstructorValue,proto3,oneof"`
}

type Pattern_LabelValue struct {
	LabelValue *Label `protobuf:"bytes,3,opt,name=label_value,json=labelValue,proto3,oneof"`
}

type Pattern_PatternValue struct {
	PatternValue *Pattern `protobuf:"bytes,4,opt,name=pattern_value,json=patternValue,proto3,oneof"`
}

func (*Pattern_TypeConstructorValue) isPattern_Pvalue() {}

func (*Pattern_LabelValue) isPattern_Pvalue() {}

func (*Pattern_PatternValue) isPattern_Pvalue() {}

func (m *Pattern) GetPvalue() isPattern_Pvalue {
	if m != nil {
		return m.Pvalue
	}
	return nil
}

func (m *Pattern) GetTypeConstructorValue() *TypeConstructor {
	if x, ok := m.GetPvalue().(*Pattern_TypeConstructorValue); ok {
		return x.TypeConstructorValue
	}
	return nil
}

func (m *Pattern) GetLabelValue() *Label {
	if x, ok := m.GetPvalue().(*Pattern_LabelValue); ok {
		return x.LabelValue
	}
	return nil
}

func (m *Pattern) GetPatternValue() *Pattern {
	if x, ok := m.GetPvalue().(*Pattern_PatternValue); ok {
		return x.PatternValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Pattern) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Pattern_TypeConstructorValue)(nil),
		(*Pattern_LabelValue)(nil),
		(*Pattern_PatternValue)(nil),
	}
}

type Argument struct {
	Ref                  int64    `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Label                *Label   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type                 *Type    `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Argument) Reset()         { *m = Argument{} }
func (m *Argument) String() string { return proto.CompactTextString(m) }
func (*Argument) ProtoMessage()    {}
func (*Argument) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{7}
}

func (m *Argument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Argument.Unmarshal(m, b)
}
func (m *Argument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Argument.Marshal(b, m, deterministic)
}
func (m *Argument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Argument.Merge(m, src)
}
func (m *Argument) XXX_Size() int {
	return xxx_messageInfo_Argument.Size(m)
}
func (m *Argument) XXX_DiscardUnknown() {
	xxx_messageInfo_Argument.DiscardUnknown(m)
}

var xxx_messageInfo_Argument proto.InternalMessageInfo

func (m *Argument) GetRef() int64 {
	if m != nil {
		return m.Ref
	}
	return 0
}

func (m *Argument) GetLabel() *Label {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *Argument) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

type Label struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Colour               string   `protobuf:"bytes,2,opt,name=colour,proto3" json:"colour,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Label) Reset()         { *m = Label{} }
func (m *Label) String() string { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()    {}
func (*Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30207954a0109b9, []int{8}
}

func (m *Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Label.Unmarshal(m, b)
}
func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Label.Marshal(b, m, deterministic)
}
func (m *Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Label.Merge(m, src)
}
func (m *Label) XXX_Size() int {
	return xxx_messageInfo_Label.Size(m)
}
func (m *Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Label) GetColour() string {
	if m != nil {
		return m.Colour
	}
	return ""
}

func init() {
	proto.RegisterEnum("Type_PrimitiveType", Type_PrimitiveType_name, Type_PrimitiveType_value)
	proto.RegisterType((*File)(nil), "File")
	proto.RegisterType((*Expression)(nil), "Expression")
	proto.RegisterType((*Expression_Hole)(nil), "Expression.Hole")
	proto.RegisterType((*Expression_Bool)(nil), "Expression.Bool")
	proto.RegisterType((*Expression_Int)(nil), "Expression.Int")
	proto.RegisterType((*Expression_Float)(nil), "Expression.Float")
	proto.RegisterType((*Expression_String)(nil), "Expression.String")
	proto.RegisterType((*Expression_List)(nil), "Expression.List")
	proto.RegisterType((*Expression_If)(nil), "Expression.If")
	proto.RegisterType((*Expression_FunctionApplication)(nil), "Expression.FunctionApplication")
	proto.RegisterType((*Expression_Ref)(nil), "Expression.Ref")
	proto.RegisterType((*Expression_ExternalRef)(nil), "Expression.ExternalRef")
	proto.RegisterType((*FunctionDefinition)(nil), "FunctionDefinition")
	proto.RegisterType((*TypeAlias)(nil), "TypeAlias")
	proto.RegisterType((*Type)(nil), "Type")
	proto.RegisterType((*Type_RefType)(nil), "Type.RefType")
	proto.RegisterType((*Type_OpaqueType)(nil), "Type.OpaqueType")
	proto.RegisterType((*Type_CompoundType)(nil), "Type.CompoundType")
	proto.RegisterType((*TypeConstructor)(nil), "TypeConstructor")
	proto.RegisterType((*Pattern)(nil), "Pattern")
	proto.RegisterType((*Argument)(nil), "Argument")
	proto.RegisterType((*Label)(nil), "Label")
}

func init() { proto.RegisterFile("proto/ast.proto", fileDescriptor_e30207954a0109b9) }

var fileDescriptor_e30207954a0109b9 = []byte{
	// 963 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x8e, 0xda, 0x46,
	0x14, 0xc6, 0x18, 0x83, 0x7d, 0xbc, 0x9b, 0xa5, 0xc3, 0x2a, 0x71, 0xbc, 0x69, 0x42, 0xa8, 0xd4,
	0x92, 0x46, 0x72, 0x9a, 0xdd, 0x56, 0xed, 0x2d, 0xbb, 0x81, 0x1a, 0x69, 0x9b, 0xa0, 0x09, 0x89,
	0x5a, 0xa9, 0x12, 0xf2, 0xb2, 0xe3, 0xd4, 0x92, 0xf1, 0xb8, 0xf6, 0x10, 0xc1, 0x45, 0x5f, 0xa5,
	0x8f, 0xd1, 0x97, 0xe8, 0xe3, 0xf4, 0x05, 0xaa, 0xf9, 0xb1, 0xb1, 0x17, 0x6e, 0xf6, 0x6e, 0xe6,
	0x7c, 0xdf, 0x37, 0x73, 0xfe, 0xe6, 0xd8, 0x70, 0x92, 0x66, 0x94, 0xd1, 0x57, 0x41, 0xce, 0x3c,
	0xb1, 0x1a, 0xfc, 0x05, 0xad, 0x49, 0x14, 0x13, 0xf4, 0x18, 0xcc, 0x84, 0x6c, 0xd8, 0x22, 0x23,
	0xa1, 0xa3, 0xf5, 0xb5, 0xa1, 0x8e, 0x3b, 0x7c, 0x8f, 0x49, 0x88, 0x10, 0xb4, 0x92, 0x60, 0x45,
	0x9c, 0x66, 0x5f, 0x1b, 0x5a, 0x58, 0xac, 0xd1, 0x04, 0x4e, 0xc3, 0x75, 0xb2, 0x64, 0x11, 0x4d,
	0x16, 0xb7, 0x24, 0x8c, 0x92, 0x88, 0x2f, 0x73, 0xc7, 0xe8, 0xeb, 0x43, 0xfb, 0xbc, 0xe7, 0x4d,
	0x14, 0xf8, 0xa6, 0xc4, 0x70, 0x2f, 0xdc, 0xb3, 0xe5, 0x83, 0xbf, 0x4d, 0x80, 0xf1, 0x26, 0xcd,
	0x48, 0x9e, 0x47, 0x34, 0x41, 0x5d, 0xd0, 0x77, 0x0e, 0xf0, 0x25, 0x7a, 0x0e, 0x36, 0x59, 0xa5,
	0x6c, 0xbb, 0xf8, 0x1c, 0xc4, 0x6b, 0xe2, 0x58, 0x7d, 0x6d, 0x68, 0xf8, 0x0d, 0x0c, 0xc2, 0xf8,
	0x91, 0xdb, 0xd0, 0x6b, 0x80, 0x1b, 0x4a, 0x63, 0xc5, 0xe0, 0x5e, 0xda, 0xe7, 0x5d, 0x6f, 0x77,
	0xaa, 0x77, 0x49, 0x69, 0xec, 0x37, 0xb0, 0xc5, 0x59, 0x52, 0xe2, 0x81, 0x15, 0x25, 0x4c, 0x29,
	0x74, 0xa1, 0x38, 0xa9, 0x2a, 0xa6, 0x09, 0xf3, 0x1b, 0xd8, 0x8c, 0x12, 0x26, 0xf9, 0xdf, 0x83,
	0x1d, 0xc6, 0x34, 0x28, 0x14, 0x2d, 0xa1, 0xf8, 0xa2, 0xaa, 0x98, 0x70, 0x98, 0x3b, 0x26, 0x78,
	0x52, 0xf5, 0x23, 0x1c, 0xe5, 0x2c, 0x8b, 0x92, 0x4f, 0x4a, 0x66, 0x08, 0x19, 0xaa, 0xca, 0xde,
	0x0b, 0xdc, 0x6f, 0x60, 0x5b, 0x32, 0xcb, 0x88, 0xe2, 0x28, 0x2f, 0x6e, 0x6b, 0xef, 0x47, 0x74,
	0x1d, 0xe5, 0xfc, 0x32, 0x8b, 0xb3, 0xa4, 0xe4, 0x25, 0x98, 0x51, 0xa8, 0x04, 0x1d, 0x21, 0x78,
	0x50, 0x0b, 0x28, 0xf4, 0x1b, 0xb8, 0x13, 0x85, 0x92, 0xbc, 0x00, 0xb7, 0xac, 0x5e, 0x90, 0xa6,
	0x71, 0xb4, 0x0c, 0xc4, 0x5a, 0xca, 0x4d, 0x21, 0x7f, 0x56, 0x8b, 0x4e, 0xb1, 0x47, 0x3b, 0xb2,
	0xdf, 0xc0, 0x4e, 0xb8, 0x6f, 0x2e, 0xf3, 0x9b, 0x91, 0xc2, 0x9d, 0xa3, 0xfd, 0xfc, 0x62, 0xc2,
	0xfd, 0x31, 0x33, 0xa2, 0x1c, 0xfa, 0x19, 0x10, 0xd9, 0x30, 0x92, 0x25, 0x41, 0xbc, 0xd8, 0x09,
	0x8f, 0x85, 0xf0, 0x51, 0x55, 0x38, 0x56, 0x2c, 0x79, 0x40, 0x97, 0xec, 0xb6, 0xe2, 0x20, 0xb7,
	0x0d, 0x2d, 0x9f, 0xc6, 0xc4, 0x7d, 0x02, 0x2d, 0x5e, 0x75, 0x74, 0x0a, 0x86, 0x3c, 0x8b, 0xb7,
	0x94, 0x89, 0xe5, 0xc6, 0x3d, 0x03, 0x7d, 0x9a, 0xb0, 0x3a, 0xa8, 0x17, 0xe0, 0x97, 0x60, 0x88,
	0x62, 0xd6, 0xe1, 0x66, 0x01, 0x3f, 0x85, 0xb6, 0x2c, 0x5a, 0x1d, 0xb7, 0x0a, 0xfc, 0x25, 0xb4,
	0x78, 0x75, 0xd0, 0x57, 0xd0, 0x16, 0x86, 0xdc, 0xd1, 0xc4, 0x9b, 0xb0, 0x2b, 0x61, 0x60, 0x05,
	0xb9, 0x11, 0x34, 0xa7, 0x21, 0x7a, 0x06, 0xad, 0x25, 0x4d, 0x6e, 0xc5, 0x39, 0x77, 0x88, 0x02,
	0xe0, 0x04, 0x96, 0x95, 0xbd, 0x5d, 0x27, 0x70, 0x00, 0x3d, 0x07, 0x23, 0x0c, 0xe2, 0xbc, 0xe8,
	0xe5, 0x1a, 0x43, 0x22, 0xee, 0xef, 0xd0, 0x3b, 0x50, 0x45, 0xe4, 0x82, 0x59, 0x54, 0x51, 0xa5,
	0xa1, 0xdc, 0xa3, 0x17, 0x60, 0x05, 0xd9, 0xa7, 0xf5, 0x8a, 0x24, 0x2c, 0x77, 0x9a, 0xfb, 0x51,
	0xec, 0x50, 0xf7, 0x11, 0xe8, 0x7c, 0x54, 0xec, 0xbd, 0x5f, 0xf7, 0x07, 0xb0, 0x2b, 0x35, 0xe3,
	0xb3, 0x24, 0x0d, 0xd8, 0x1f, 0x2a, 0x65, 0x62, 0x7d, 0x68, 0xbe, 0x5c, 0x76, 0x54, 0x6e, 0x07,
	0xff, 0x68, 0x80, 0xf6, 0x87, 0xc9, 0x81, 0x41, 0xf1, 0x04, 0x8c, 0x38, 0xb8, 0x21, 0xb1, 0x4a,
	0x52, 0xdb, 0xbb, 0xe6, 0x3b, 0x2c, 0x8d, 0xe8, 0x9b, 0x6a, 0x28, 0xba, 0x08, 0xc5, 0xf2, 0x46,
	0xca, 0x52, 0x09, 0x04, 0x7d, 0x0d, 0x76, 0x46, 0xd8, 0x3a, 0x4b, 0x16, 0x6c, 0x9b, 0x16, 0x2f,
	0xdd, 0xf0, 0xe6, 0xdb, 0x94, 0x60, 0x90, 0x08, 0x5f, 0xf3, 0x92, 0xdc, 0xd0, 0xdb, 0xad, 0x7a,
	0xd3, 0xf5, 0x92, 0x70, 0x60, 0xf0, 0x2b, 0x58, 0x9c, 0x38, 0x8a, 0xa3, 0x20, 0xbf, 0xb7, 0xbb,
	0x67, 0x60, 0xf0, 0xeb, 0x5f, 0x3b, 0xa7, 0xd5, 0xfb, 0xa5, 0x6d, 0xf0, 0x5f, 0x13, 0x5a, 0xc2,
	0x87, 0xfd, 0x53, 0x2f, 0xc0, 0x4a, 0xb3, 0x68, 0x15, 0xb1, 0xe8, 0x33, 0x71, 0xa0, 0xaf, 0x0d,
	0x1f, 0x9c, 0xf7, 0x84, 0xd6, 0x9b, 0x15, 0x66, 0xbe, 0xe3, 0xa3, 0xa3, 0xe4, 0xa1, 0xef, 0xc0,
	0x5c, 0xd2, 0x55, 0x4a, 0xd7, 0xc9, 0xad, 0x63, 0xab, 0x11, 0x25, 0x34, 0x57, 0xca, 0xaa, 0x24,
	0x25, 0x0b, 0x7d, 0x0b, 0xfc, 0xe9, 0xca, 0x0c, 0xc9, 0xd7, 0x7d, 0x2c, 0x15, 0x98, 0x84, 0x8a,
	0xdc, 0xc9, 0xe4, 0xd2, 0x3d, 0x83, 0x8e, 0xb2, 0x1e, 0xe8, 0x8e, 0x3e, 0xc0, 0xbb, 0x34, 0xf8,
	0x73, 0x2d, 0xbc, 0x2a, 0x1b, 0x41, 0xdb, 0x35, 0x82, 0xfb, 0x13, 0x1c, 0x55, 0xdd, 0x40, 0x3d,
	0xd0, 0x36, 0xea, 0xa1, 0xa8, 0xac, 0x68, 0x1b, 0x6e, 0xdc, 0xaa, 0x44, 0x16, 0xc6, 0xed, 0xe0,
	0x0a, 0x8e, 0x6b, 0x41, 0xa3, 0xa7, 0xe0, 0xce, 0xf0, 0xf4, 0x97, 0xe9, 0x7c, 0xfa, 0x71, 0xbc,
	0x98, 0xff, 0x36, 0x1b, 0x2f, 0x3e, 0xbc, 0x7d, 0x3f, 0x1b, 0x5f, 0x4d, 0x27, 0xd3, 0xf1, 0x9b,
	0x6e, 0x03, 0x75, 0x40, 0x9f, 0xbe, 0x9d, 0x77, 0x35, 0x64, 0x81, 0x31, 0xb9, 0x7e, 0x37, 0x9a,
	0x77, 0x9b, 0x97, 0x26, 0xb4, 0x99, 0x6c, 0xc4, 0x11, 0x9c, 0xf0, 0x53, 0xae, 0x68, 0x92, 0xb3,
	0x6c, 0xbd, 0x64, 0x34, 0xbb, 0x6f, 0x55, 0x07, 0xff, 0x6a, 0xd0, 0x99, 0x05, 0x8c, 0xbf, 0x86,
	0x03, 0x5a, 0x1f, 0x1e, 0xf2, 0x84, 0x2e, 0x96, 0xbb, 0x1b, 0xee, 0x7c, 0xd2, 0xee, 0xdc, 0xef,
	0x37, 0xf0, 0x29, 0xab, 0x9b, 0xe4, 0x34, 0x7d, 0x01, 0xb6, 0xb8, 0xb0, 0xf6, 0x7d, 0x53, 0xbe,
	0xf0, 0x4f, 0x94, 0x00, 0x25, 0xf5, 0x15, 0x1c, 0xa7, 0xd2, 0xa3, 0xda, 0xa7, 0xcd, 0xf4, 0x94,
	0x9f, 0x7e, 0x03, 0x1f, 0x29, 0x82, 0x10, 0xf0, 0x84, 0xa4, 0x32, 0x21, 0x1f, 0xc0, 0x2c, 0x1e,
	0xd0, 0xbd, 0xfb, 0xfb, 0x31, 0xb4, 0x44, 0xf3, 0xe8, 0xd5, 0x9a, 0x09, 0xd3, 0xe0, 0x02, 0x0c,
	0x41, 0x3d, 0xd4, 0x0d, 0xe8, 0x21, 0xb4, 0x97, 0x34, 0xa6, 0xeb, 0x4c, 0x0d, 0x0b, 0xb5, 0xbb,
	0x69, 0x8b, 0x9f, 0x99, 0x8b, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x40, 0x64, 0xee, 0xdf,
	0x08, 0x00, 0x00,
}
