// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

package ast

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetFileRequest struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *GetFileRequest) Reset()                    { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()               {}
func (*GetFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type GetFileResponse struct {
	JsonContent string `protobuf:"bytes,1,opt,name=json_content,json=jsonContent" json:"json_content,omitempty"`
}

func (m *GetFileResponse) Reset()                    { *m = GetFileResponse{} }
func (m *GetFileResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFileResponse) ProtoMessage()               {}
func (*GetFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type UpdateFileRequest struct {
	Path        string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	JsonContent string `protobuf:"bytes,2,opt,name=json_content,json=jsonContent" json:"json_content,omitempty"`
	ElmContent  string `protobuf:"bytes,3,opt,name=elm_content,json=elmContent" json:"elm_content,omitempty"`
}

func (m *UpdateFileRequest) Reset()                    { *m = UpdateFileRequest{} }
func (m *UpdateFileRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateFileRequest) ProtoMessage()               {}
func (*UpdateFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func init() {
	proto.RegisterType((*GetFileRequest)(nil), "ast.GetFileRequest")
	proto.RegisterType((*GetFileResponse)(nil), "ast.GetFileResponse")
	proto.RegisterType((*UpdateFileRequest)(nil), "ast.UpdateFileRequest")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0x2e, 0x51, 0x52, 0xe1,
	0xe2, 0x73, 0x4f, 0x2d, 0x71, 0xcb, 0xcc, 0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0x12, 0xe2, 0x62, 0x29, 0x48, 0x2c, 0xc9, 0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3,
	0x95, 0x4c, 0xb8, 0xf8, 0xe1, 0xaa, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x14, 0xb9, 0x78,
	0xb2, 0x8a, 0xf3, 0xf3, 0xe2, 0x93, 0xf3, 0xf3, 0x4a, 0x52, 0xf3, 0x4a, 0xa0, 0xca, 0xb9, 0x41,
	0x62, 0xce, 0x10, 0x21, 0xa5, 0x6c, 0x2e, 0xc1, 0xd0, 0x82, 0x94, 0xc4, 0x92, 0x54, 0x02, 0xc6,
	0x63, 0x98, 0xc5, 0x84, 0x61, 0x96, 0x90, 0x3c, 0x17, 0x77, 0x6a, 0x4e, 0x2e, 0x5c, 0x05, 0x33,
	0x58, 0x05, 0x17, 0x50, 0x08, 0xaa, 0x20, 0x89, 0x0d, 0xec, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa9, 0x63, 0x1b, 0x20, 0xe4, 0x00, 0x00, 0x00,
}
